env:
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "airbnb-base"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module

  # https://github.com/jest-community/eslint-plugin-jest
  # https://github.com/babel/eslint-plugin-babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments

# https://github.com/babel/babel-eslint
parser: babel-eslint

rules:
  no-console: 0
